[project]
name = "campusx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.4.0",
    "langchain-mistralai>=1.1.6",
    "langgraph>=1.2.12",
    "python-dotenv>=1.2.3",
]

[project.scripts]
campusx = "campusx:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
